services:
  backend:
    build:
      context: ./Backend #location of Dockerfile
    command: gunicorn crud.wggi --bind 0.0.0.0:8000
    restart: unless-stopped
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./Frontend
    restart: unless-stopped
    volumes:
      - frontend:/app/build

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend:/var/www/Frontend
    depends_on:
      - backend
      - frontend
volumes:
  frontend:
